name: mmkv_ios
description: iOS platform implementation of MMKV.
repository: https://github.com/Tencent/MMKV/tree/master/flutter/mmkv_ios
version: 2.0.0
homepage: https://github.com/Tencent/mmkv

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0
  mmkv_platform_interface:
    ^2.0.0
#    path: ../mmkv_platform_interface

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: mmkv
    platforms:
      ios:
        pluginClass: MMKVPlugin
        dartPluginClass: MMKVPlatformIOS
