name: mmkv_ohos
description: OHOS platform implementation of MMKV.
repository: https://github.com/Tencent/MMKV/tree/master/flutter/mmkv_ohos
version: 2.0.0
homepage: https://github.com/Tencent/mmkv

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  path_provider: ^2.0.1
#  path_provider_ohos:
#    git:
#      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
#      path: "packages/path_provider/path_provider_ohos"
  ffi: ^2.0.0
  mmkv_platform_interface:
    ^2.0.0
#    path: ../mmkv_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: mmkv
    platforms:
      ohos:
        package: com.tencent.mmkv
        pluginClass: MMKVPlugin
        dartPluginClass: MMKVPlatformOHOS
